== Followed the steps listed here

This repository contains an abridged version of the following tutorial:

https://codeburst.io/getting-started-with-flow-and-nodejs-b8442d3d2e57


== Install node and npm using Homebrew

TIP: Think node => java, npm => maven

....
awong@mbp:~/study/notes/flow $ brew install node
awong@mbp:~/study/notes/flow $ node --version
v12.6.0
awong@mbp:~/study/notes/flow $ npm --version
6.14.2
....


== Create the repository

TIP: Think npm init => mvn archetype:generate -DarchetypeArtifactId=maven-archetype-quickstart 

....
awong@mbp:~/study/notes/flow $ npm init --yes
....

== Install flow to the project and save it as a development dependency:

TIP: Instead of storing the downloaded libraries in ~/.m2 directory, node modules
are installed in the node_modules subdirectory.

....
awong@mbp:~/study/notes/flow $ npm install flow-bin -SD
awong@mbp:~/study/notes/flow $ npm install flow-remove-types -SD
awong@mbp:~/study/notes/flow $ npm install flow-typed -SD
....


== Configure flow

TIP: This is just like configuring a custom maven plugin

....
awong@mbp:~/study/notes/flow $ touch .flowconfig
....

Populate .flowconfig with settings

....
[ignore]
.*/node_modules/.*
[include]
[libs]
flow-typed
[options]
all=true
....


== Create custom build targets for npm

TIP: Think package.json => pom.xml

Add the following to package.json:

....
"scripts": {
  "flow": "flow",
  "flow:check": "flow check ./src/",
  "flow:build": "flow-remove-types ./src/ -d ./lib/ --all --pretty",
}
....

These are custom commands that you can run by calling:

....
npm run {command-name}
....


== Create the source code

....
awong@mbp:~/study/notes/flow $ mkdir src
awong@mbp:~/study/notes/flow $ touch src/index.js
....

Populate src/index.js with the following

....
type Point2d = {|
  x: number,
  y: number
|};
const myPoint: Point2d = {
  X: 1,
  y: 2
};
console.log(myPoint.x, myPoint.y);
....


== Try running flow

Try running the type checking and stripping away the type information.

....
awong@mbp:~/study/notes/flow $ npm run flow:check
awong@mbp:~/study/notes/flow $ npm run flow:build
....
